# Generated by Django 4.2.1 on 2023-12-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compnay',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_email', models.EmailField(max_length=50)),
                ('c_password', models.CharField(max_length=50)),
                ('c_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='templates',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=50)),
                ('t_img', models.ImageField(default='', upload_to='img')),
                ('t_file', models.FileField(default='', upload_to='templates')),
            ],
        ),
        migrations.CreateModel(
            name='User_t',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('qualification', models.CharField(default=' ', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='job_vacancy',
            fields=[
                ('jv_id', models.AutoField(primary_key=True, serialize=False)),
                ('jv_name', models.CharField(max_length=50)),
                ('jv_date', models.DateField()),
                ('jv_description', models.TextField(max_length=500)),
                ('jv_location', models.CharField(max_length=50)),
                ('jv_no_of_vacancy', models.IntegerField(default=0)),
                ('jv_eligibility', models.CharField(max_length=50)),
                ('jv_exprince', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.compnay')),
            ],
        ),
        migrations.CreateModel(
            name='apply_job',
            fields=[
                ('aj_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_date', models.DateField()),
                ('resume', models.FileField(default='', upload_to='resume')),
                ('jv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.job_vacancy')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.user_t')),
            ],
        ),
    ]
