# Generated by Django 4.2.1 on 2023-12-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_t',
            table='User_t',
        ),
    ]
