# Generated by Django 4.2.1 on 2023-12-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_user_t_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_t',
            table=None,
        ),
    ]
