# Generated by Django 4.2.1 on 2024-01-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_user_t_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_vacancy',
            name='c_id',
        ),
        migrations.DeleteModel(
            name='apply_job',
        ),
        migrations.DeleteModel(
            name='compnay',
        ),
        migrations.DeleteModel(
            name='job_vacancy',
        ),
    ]
