# Generated by Django 4.2.1 on 2024-01-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_compnay_job_vacancy_apply_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compnay',
            new_name='company',
        ),
    ]
