# Generated by Django 4.2.1 on 2024-01-27 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0006_rename_compnay_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(default='Compnay', max_length=100),
        ),
        migrations.AddField(
            model_name='user_t',
            name='type',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='templates',
            name='t_img',
            field=models.ImageField(default=' ', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='user_t',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
