# Generated by Django 4.2.1 on 2024-01-27 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0008_alter_company_c_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user_t',
            name='type',
        ),
        migrations.AlterField(
            model_name='company',
            name='c_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', unique=True),
        ),
    ]
