# Generated by Django 4.2.1 on 2024-01-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_company_c_email_alter_user_t_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='c_img',
            field=models.ImageField(default=' ', upload_to='img'),
        ),
    ]
