# Generated by Django 4.2.1 on 2024-01-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_company_c_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_t',
            name='u_img',
            field=models.ImageField(default='images/user.png', upload_to='images/user/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='c_img',
            field=models.ImageField(default='images/user.png', upload_to='images/compnay/'),
        ),
    ]
