# Generated by Django 4.2.1 on 2024-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_user_t_u_img_alter_company_c_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='resume',
            field=models.FileField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='c_img',
            field=models.ImageField(default='images/company.png', upload_to='images/compnay/'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='t_file',
            field=models.FileField(upload_to='templates_pdf/'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='t_img',
            field=models.ImageField(upload_to='pdf_img/'),
        ),
    ]
