# Generated by Django 4.2.1 on 2024-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_alter_apply_job_resume_alter_company_c_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='t_img',
            field=models.FileField(upload_to='pdf_img/'),
        ),
    ]
