# Generated by Django 4.2.1 on 2024-01-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_templates_t_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='t_img',
            field=models.FileField(upload_to='t_img/'),
        ),
    ]
