# Generated by Django 4.2.1 on 2024-01-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_alter_templates_t_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='t_img',
        ),
    ]
