# Generated by Django 4.2.1 on 2024-02-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_templates_t_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_t',
            name='instrgram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_t',
            name='linkdin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_t',
            name='profession',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_t',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='a_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='c_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
