# Generated by Django 4.2.1 on 2024-02-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_user_t_instrgram_user_t_linkdin_user_t_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='jv_id',
        ),
        migrations.DeleteModel(
            name='job_vacancy',
        ),
    ]
