# Generated by Django 4.2.1 on 2024-02-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_remove_apply_job_jv_id_delete_job_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_vacancy',
            fields=[
                ('jv_id', models.AutoField(primary_key=True, serialize=False)),
                ('jv_name', models.CharField(default='', max_length=50)),
                ('jv_category', models.CharField(default='', max_length=50)),
                ('jv_time', models.CharField(default='', max_length=50)),
                ('jv_location', models.CharField(default='', max_length=50)),
                ('jv_city', models.CharField(default='', max_length=50)),
                ('jv_pincode', models.CharField(default='', max_length=50)),
                ('jv_salary', models.CharField(default='none', max_length=50)),
                ('jv_exprince', models.CharField(default='fresher', max_length=50)),
                ('jv_function', models.CharField(default='', max_length=50)),
                ('jv_description', models.TextField(default='', max_length=100000)),
                ('jv_key_responsibilites', models.TextField(default='', max_length=100000)),
                ('jv_requirements', models.TextField(default='', max_length=100000)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.company')),
            ],
        ),
        migrations.AddField(
            model_name='apply_job',
            name='jv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.job_vacancy'),
            preserve_default=False,
        ),
    ]
