# Generated by Django 4.2.1 on 2024-02-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_alter_job_vacancy_jv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_vacancy',
            name='jv_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
