# Generated by Django 4.2.1 on 2024-02-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_alter_job_vacancy_jv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='instrgram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='linkdin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
    ]
