# Generated by Django 4.2.1 on 2024-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_company_instrgram_company_linkdin_company_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='a_date',
        ),
        migrations.AddField(
            model_name='apply_job',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='zip',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='resume',
            field=models.FileField(default='', upload_to='images/resume'),
        ),
    ]
