# Generated by Django 4.2.1 on 2024-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0028_apply_job_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_t',
            name='resume',
            field=models.FileField(default='', upload_to='media/resume/'),
        ),
    ]
