# Generated by Django 4.2.1 on 2024-02-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0031_alter_user_t_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_t',
            name='resume',
            field=models.FileField(default='', upload_to='images/u_resume/'),
        ),
    ]
