# Generated by Django 4.2.1 on 2024-02-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0032_alter_user_t_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_t',
            name='resume',
            field=models.FileField(default='', upload_to='u_resume/'),
        ),
    ]
