# Generated by Django 4.2.1 on 2024-02-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0036_user_t_r_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_t',
            name='r_img',
            field=models.ImageField(default='', upload_to='r_img/'),
        ),
    ]
