# Generated by Django 4.2.1 on 2024-02-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0037_user_t_r_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_t',
            name='r_img',
            field=models.ImageField(default='', upload_to='img_r/'),
        ),
    ]
